default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: moyoriru_development

test:
  <<: *default
  database: moyoriru_test

production:
  <<: *default
  database: moyoriru_production
  username: moyoriru
  password: <%= ENV['MOYORIRU_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
